trigger: none

variables:
- group: database-string

stages:
- stage: Deploy_Production
  displayName: Deploy to Production

  jobs:
  - deployment: DeployFastAPI
    displayName: FastAPI Deployment

    environment:
      name: dev-backend
      resourceType: VirtualMachine
      resourceName: backend-vm

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          # 🔹 Step 1: Copy code
          - script: |
              echo "Installing Python if missing..."
              sudo apt-get update -y
              sudo apt-get install -y python3 python3-venv python3-pip

              echo "Verifying Python..."
              which python3
              python3 --version

              cd ~/fastapi-app

              # Remove broken venv (IMPORTANT)
              if [ -d "venv" ]; then
                echo "Removing old venv..."
                rm -rf venv
              fi

              echo "Creating fresh virtual environment..."
              python3 -m venv venv

              # Activate venv
              source venv/bin/activate

              echo "Checking python inside venv..."
              which python

              # Install dependencies properly
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt

            displayName: Setup Python Environment