trigger:
  branches:
    include:
      - main

pool: practice-pool

# variables:
# - group: DB-SECRETS   # Variable Group name

stages:
- stage: CI
  displayName: "Build & Run Python App"
  jobs:
  - job: build
    displayName: "Install, Run & Test"
    steps:

    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    - task: PowerShell@2
      displayName: "Install ODBC & SQL Server Driver"
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg2 unixodbc unixodbc-dev
          
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
          | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
          | sudo tee /etc/apt/sources.list.d/mssql-release.list
          
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18


    - task: PowerShell@2
      displayName: "Install Python Dependencies"
      inputs:
        targetType: inline
        script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - task: PowerShell@2
      displayName: "Run Application"
      env:
        DB_CONNECTION_STRING: $(DB_CONNECTION_STRING)
      inputs:
        targetType: inline
        script: |
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 10

    - task: PowerShell@2
      displayName: "API Health Check"
      inputs:
        targetType: inline
        script: |
          curl http://localhost:8000/api/ || exit 1
