trigger: 
  branches:
   include:
     - master

variables:
- group: New variable group 28-Jan

stages:
- stage: Deploy_Production
  displayName: Deploy to Production
  jobs:
  - deployment: DeployFastAPI
    displayName: FastAPI Deployment
    environment:
      name: production
      resourceType: VirtualMachine
      resourceName: backend-vm

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: |
             echo "===== Updating OS ====="
             sudo apt-get update -y
            displayName: OS Update

          - script: |
              sudo apt-get install -y curl gnupg2 unixodbc unixodbc-dev python3-full python3-venv
            displayName: Install system deps

          - script: |
              curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
              echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
              sudo apt-get update
              sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
            displayName: Install MS SQL ODBC

          - script: |
              python3 -m venv venv
              source venv/bin/activate

              pip install --upgrade pip
              pip install -r requirements.txt

              python app.py
            displayName: Setup Python venv and install deps
            env:
              CONNECTION_STRING: $(CONNECTION_STRING)

            
          - script: |
              sudo systemctl stop fastapi || true
              sudo systemctl start fastapi
            displayName: Restart FastAPI Service